# Defined in commandlineArgument of agent-test pom.xml

server:
  port: 18080

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /

spring:
  redis:
    cluster:
      nodes:
        - 10.168.240.229:18001
        - 10.168.240.229:18002
        - 10.168.240.229:18003
